[package]
name = "yogi"
version = "0.2.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.7"
imprint = { git = "https://github.com/archer884/imprint" }
structopt = "0.3"
walkdir = "2.3"
