[package]
name = "yogi"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

[dependencies]
digest = "0.7.2"
sha2 = "0.7.0"
walkdir = "2.1.3"
picnic = { git = "https://github.com/archer884/picnic" }
